name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    if: false # off until this is resolved https://github.com/actions/virtual-environments/issues/2486
    runs-on: macos-11.0
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, macOS]
        action: [test, archive]
        include:
          - platform: iOS
            action: test
            destination: "'platform=iOS Simulator,name=iPhone 8,OS=14.4'"

          - platform: iOS
            action: archive
            destination: "'generic/platform=iOS'"

          - platform: macOS
            action: test
            destination: "'platform=macOS,arch=x86_64'"

          - platform: macOS
            action: archive
            destination: "'platform=macOS,arch=x86_64'"
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install xcbeautify

    - name: ${{ matrix.platform }} ${{ matrix.action }}
      run: |
        NSUnbufferedIO=YES \
        xcodebuild clean ${{ matrix.action }} \
          -destination ${{ matrix.destination }} \
          -scheme TextBuilder \
          2>&1 | xcbeautify
