name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, macOS]
        action: [test, archive]
        include:
          - platform: iOS
            action: test
            destination: "'platform=iOS Simulator,name=iPhone 8,OS=14.5'"

          - platform: iOS
            action: archive
            destination: "'generic/platform=iOS'"

          - platform: macOS
            action: test
            destination: "'platform=macOS,arch=x86_64'"

          - platform: macOS
            action: archive
            destination: "'platform=macOS,arch=x86_64'"
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install xcbeautify

    - name: ${{ matrix.platform }} ${{ matrix.action }}
      run: |
        set -o pipefail && \
        xcodebuild clean ${{ matrix.action }} \
          -destination ${{ matrix.destination }} \
          -scheme TextBuilder \
          | xcbeautify
