name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.platform }}
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - macOS
          - tvOS
        include:
          - platform: iOS
            destination: "'platform=iOS Simulator,name=iPhone 8,OS=15.2'"
          - platform: macOS
            destination: "'platform=macOS,arch=x86_64'"
          - platform: tvOS
            destination: "'platform=tvOS Simulator,name=Apple TV,OS=15.2'"
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Run Tests
      run: |
        set -o pipefail && \
        xcodebuild clean test \
          -destination ${{ matrix.destination }} \
          -scheme TextBuilder \
          | xcpretty
